# Generated by Django 4.0.1 on 2022-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrot',
            name='avatar',
            field=models.URLField(default='none', verbose_name='Аватар'),
        ),
    ]
